/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import components.AddContent;
import components.FormatJtable;
import components.Formater;
import components.PnlHangHoaInfo;
import components.ResizeContent;
import dao.LoHangDao;
import db.ConnectDB;
import entities.*;
/**
 *
 * @author Admin
 */
public class LoHangPage extends javax.swing.JPanel {

    
	private DefaultTableModel model_NCC;
	private JTable tbl_NCC;

	private LoHangDao loHang_dao = new LoHangDao();

	
	/**
     * Creates new form NhanVien_httk
     */
    public LoHangPage()  {
        initComponents(); 
        ResizeContent.resizeContent(this);
        addTableNCC();

    }

	private void addTableNCC() {
		// TODO Auto-generated method stub
    	String[] colNames = {"STT","Số lô", "Mã hàng hóa", "Tên hàng hóa", "Số lượng",  "Ngày sản xuất","Hạn sử dụng","Giá nhập","Ngày nhập"};
        
        model_NCC = new DefaultTableModel(colNames, 0);
        tbl_NCC = new JTable(model_NCC);
        FormatJtable.setFontJtable(tbl_NCC);
        JScrollPane js_tableHangHoa = new JScrollPane(tbl_NCC);
        
        if (tbl_NCC.getColumnModel().getColumnCount() > 0) {
        	tbl_NCC.getColumnModel().getColumn(0).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(1).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(2).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(3).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(4).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(5).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(6).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(7).setResizable(false);
        	tbl_NCC.getColumnModel().getColumn(8).setResizable(false);
            
        }
        
        JTableHeader headerTable =  tbl_NCC.getTableHeader();
		headerTable.setPreferredSize(new Dimension(headerTable.getPreferredSize().width, 40));
		tbl_NCC.setRowHeight(40);

        pnlCenter.add(js_tableHangHoa, BorderLayout.CENTER);
        List<LoHang> dsLo = loHang_dao.getLoHangTheoMaHH(PnlHangHoaInfo.hangHoaInfo.txt_maHangHoa.getText());
        FormatJtable.setCellEditable(tbl_NCC);
        int stt = 1;
        jLabel1.setText(dsLo.size()+"");
        for (LoHang lo : dsLo) {
			model_NCC.addRow(new Object[] {stt++,lo.getSoLo(),lo.getHangHoa().getMaHangHoa(),lo.getHangHoa().getTenHangHoa(),
					lo.getSoLuong(),Formater.dateFormater(lo.getNgaySanXuat()),Formater.dateFormater(lo.getHanSuDung()),Formater.decimalFormat(lo.getGiaNhap()),Formater.dateFormater(lo.getNgayNhap())});
		}

	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCenter = new javax.swing.JPanel();
        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 840));
        setLayout(new java.awt.BorderLayout());

        pnlCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlNorth.setBackground(new java.awt.Color(255, 255, 255));
        pnlNorth.setPreferredSize(new java.awt.Dimension(1450, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel1.setText("Danh sách:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Danh sách lô hàng");

        btn_thoat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 1860, Short.MAX_VALUE))
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_thoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pnlCenter.add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        add(pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(PnlHangHoaInfo.hangHoaInfo);
    }//GEN-LAST:event_btn_thoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    // End of variables declaration//GEN-END:variables
    
   
  
 
    
       
       
}
