/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import components.AddContent;
import components.ColorSample;

import components.PnlBanHang;
import components.StatusMenu;


/**
 *
 * @author LENOVO
 */
public class RootFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public RootFrame() {
    	setTitle("Phầm mềm quản lý bán hàng VDK");
        initComponents();
        Image img = new ImageIcon(getClass().getResource("/icon/logo2.png")).getImage();
        setIconImage(img);
        pnlContent.add(new TrangChu());
        AddContent.setContent(pnlContent);
        resizeFrameToScreenScale();
        setFontAll(new Font(lblUser.getName(), Font.PLAIN, 14));
        lblUser.setText("Admin");
        
    }
 // Hàm này sẽ điều chỉnh kích thước frame sao cho phù hợp với tỷ lệ scale của màn hình
    private void resizeFrameToScreenScale() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); // Lấy kích thước màn hình
        setPreferredSize(screenSize);
        setSize(screenSize); 
        pnlMain.setPreferredSize(screenSize);
//        jPanelContent.setPreferredSize(screenSize);
//        jPanelFooter.setPreferredSize(new Dimension((int)screenSize.getWidth(),30));
//        jPanelHeader.setPreferredSize(new Dimension(1400,60));
//        jPanelMenu.setPreferredSize(new Dimension((int)screenSize.getWidth(),70));
//        
//        System.out.println(screenSize);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlHeaderTop = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTienIch = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlHeaderMenu = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnQLDonHang = new javax.swing.JButton();
        btnQLHangHoa = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlContent = new javax.swing.JPanel();
        Drop4 = new javax.swing.JPanel();
        btnHangHoa = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnXuatTra = new javax.swing.JButton();
        Drop7 = new javax.swing.JPanel();
        btnTheoHangHoa = new javax.swing.JButton();
        btnTheoCP = new javax.swing.JButton();
        btnTheoLN = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setAlignmentX(0.0F);
        pnlMain.setAlignmentY(0.0F);
        pnlMain.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMainMouseEntered(evt);
            }
        });
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(193, 219, 208));
        pnlHeader.setAlignmentX(0.0F);
        pnlHeader.setAlignmentY(0.0F);
        pnlHeader.setPreferredSize(new java.awt.Dimension(1920, 130));

        pnlHeaderTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeaderTop.setPreferredSize(new java.awt.Dimension(1920, 60));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoStore_small.png"))); // NOI18N

        lblTienIch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-setting-32.png"))); // NOI18N
        lblTienIch.setText("Tiện ích");
        lblTienIch.setAlignmentY(0.0F);
        lblTienIch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTienIchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTienIchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTienIchMouseExited(evt);
            }
        });

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-avatar-32.png"))); // NOI18N
        lblUser.setText("Username");
        lblUser.setPreferredSize(new java.awt.Dimension(100, 60));
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderTopLayout = new javax.swing.GroupLayout(pnlHeaderTop);
        pnlHeaderTop.setLayout(pnlHeaderTopLayout);
        pnlHeaderTopLayout.setHorizontalGroup(
            pnlHeaderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderTopLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienIch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderTopLayout.setVerticalGroup(
            pnlHeaderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderTopLayout.createSequentialGroup()
                .addGroup(pnlHeaderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTienIch))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap())
        );

        pnlHeaderMenu.setBackground(new java.awt.Color(193, 219, 208));
        pnlHeaderMenu.setAlignmentX(0.0F);
        pnlHeaderMenu.setAlignmentY(0.0F);
        pnlHeaderMenu.setPreferredSize(new java.awt.Dimension(1920, 60));

        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-overview-32.png"))); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-overview-32.png"))); // NOI18N
        btnTrangChu.setBackground(ColorSample.gb);
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setPreferredSize(new java.awt.Dimension(150, 50));
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnTrangChu);

        btnBanHang.setBackground(new java.awt.Color(193, 219, 208,0));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sell-32.png"))); // NOI18N
        btnBanHang.setText("Bán hàng");
        btnBanHang.setBorderPainted(false);
        btnBanHang.setPreferredSize(new java.awt.Dimension(150, 50));
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanHangMouseExited(evt);
            }
        });
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnBanHang);

        btnQLDonHang.setBackground(new java.awt.Color(193, 219, 208,0));
        btnQLDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-bill-32.png"))); // NOI18N
        btnQLDonHang.setText("Quản lý đơn hàng");
        btnQLDonHang.setBorderPainted(false);
        btnQLDonHang.setPreferredSize(new java.awt.Dimension(200, 50));
        btnQLDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLDonHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLDonHangMouseExited(evt);
            }
        });
        btnQLDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonHangActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnQLDonHang);

        btnQLHangHoa.setBackground(new java.awt.Color(193, 219, 208,0));
        btnQLHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-product-32.png"))); // NOI18N
        btnQLHangHoa.setText("Quản lý hàng hóa ▾");
        btnQLHangHoa.setBorderPainted(false);
        btnQLHangHoa.setPreferredSize(new java.awt.Dimension(200, 50));
        btnQLHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLHangHoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLHangHoaMouseExited(evt);
            }
        });
        btnQLHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHangHoaActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnQLHangHoa);

        btnThongKe.setBackground(new java.awt.Color(193, 219, 208,0));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-graph-report-script-32.png"))); // NOI18N
        btnThongKe.setText("Thống kê ▾");
        btnThongKe.setBorderPainted(false);
        btnThongKe.setPreferredSize(new java.awt.Dimension(150, 50));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        pnlHeaderMenu.add(btnThongKe);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeaderTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHeaderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlHeaderTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHeaderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMain.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setAlignmentX(0.0F);
        pnlBody.setAlignmentY(0.0F);
        pnlBody.setPreferredSize(new java.awt.Dimension(1920, 140));
        pnlBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBodyMouseClicked(evt);
            }
        });
        pnlBody.setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setAlignmentX(0.0F);
        jLayeredPane1.setAlignmentY(0.0F);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setAlignmentX(0.0F);
        pnlContent.setAlignmentY(0.0F);
        pnlContent.setLayout(new java.awt.BorderLayout());

        Drop4.setBackground(new java.awt.Color(193, 219, 208));
        Drop4.setPreferredSize(new java.awt.Dimension(200, 200));

        btnHangHoa.setBackground(new java.awt.Color(193, 219, 208));
        btnHangHoa.setText("Hàng hóa");
        btnHangHoa.setBorderPainted(false);
        btnHangHoa.setPreferredSize(new java.awt.Dimension(200, 40));
        btnHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangHoaActionPerformed(evt);
            }
        });

        btnNhapHang.setBackground(new java.awt.Color(193, 219, 208));
        btnNhapHang.setText("Nhập hàng");
        btnNhapHang.setBorderPainted(false);
        btnNhapHang.setPreferredSize(new java.awt.Dimension(200, 40));
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnXuatTra.setBackground(new java.awt.Color(193, 219, 208));
        btnXuatTra.setText("Xuất trả");
        btnXuatTra.setBorderPainted(false);
        btnXuatTra.setPreferredSize(new java.awt.Dimension(200, 40));
        btnXuatTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop4Layout = new javax.swing.GroupLayout(Drop4);
        Drop4.setLayout(Drop4Layout);
        Drop4Layout.setHorizontalGroup(
            Drop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop4Layout.createSequentialGroup()
                .addGroup(Drop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Drop4Layout.setVerticalGroup(
            Drop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop4Layout.createSequentialGroup()
                .addComponent(btnHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Drop7.setBackground(new java.awt.Color(193, 219, 208));
        Drop7.setPreferredSize(new java.awt.Dimension(150, 200));

        btnTheoHangHoa.setBackground(new java.awt.Color(193, 219, 208));
        btnTheoHangHoa.setText("Theo hàng hóa");
        btnTheoHangHoa.setBorderPainted(false);
        btnTheoHangHoa.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTheoHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheoHangHoaActionPerformed(evt);
            }
        });

        btnTheoCP.setBackground(new java.awt.Color(193, 219, 208));
        btnTheoCP.setText("Chi Phí Nhập");
        btnTheoCP.setBorderPainted(false);
        btnTheoCP.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTheoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheoCPActionPerformed(evt);
            }
        });

        btnTheoLN.setBackground(new java.awt.Color(193, 219, 208));
        btnTheoLN.setText("Theo lợi nhuận");
        btnTheoLN.setBorderPainted(false);
        btnTheoLN.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTheoLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheoLNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Drop7Layout = new javax.swing.GroupLayout(Drop7);
        Drop7.setLayout(Drop7Layout);
        Drop7Layout.setHorizontalGroup(
            Drop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop7Layout.createSequentialGroup()
                .addGroup(Drop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTheoHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTheoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTheoLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Drop7Layout.setVerticalGroup(
            Drop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Drop7Layout.createSequentialGroup()
                .addComponent(btnTheoHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTheoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTheoLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(pnlContent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Drop4, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.setLayer(Drop7, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Drop4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1714, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(Drop7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1739, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Drop7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(870, Short.MAX_VALUE)))
        );

        pnlBody.add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pnlMain.add(pnlBody, java.awt.BorderLayout.CENTER);

        pnlFooter.setPreferredSize(new java.awt.Dimension(1920, 30));

        lblFooter.setText("Phầm mềm quản lý hiệu thuốc tây K3TD - ver1.0.0");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblFooter)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFooterLayout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(lblFooter)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        pnlMain.add(pnlFooter, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pnlMainMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    	
    }  
    private void btnCaLamViecActionPerformed(java.awt.event.ActionEvent evt) {
    	hideAllDropMenu();
    }     
    
    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	AddContent.addContent(new TrangChu());
    }                                           

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
    	AddContent.addContent(PnlBanHang.bh1);
    }//GEN-LAST:event_btnBanHangActionPerformed
   
    private void hideAllDropMenu(){
        StatusMenu.temp3 = false;
        StatusMenu.temp4 = false; 
        StatusMenu.temp5 = false; 
        StatusMenu.temp6 = false; 
        StatusMenu.temp7 = false; 

        Drop4.setSize(0, 0);
     
   
        Drop7.setSize(0, 0);
    }
    private void btnQLDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonHangActionPerformed

        AddContent.addContent(new HoaDonPage());
    }//GEN-LAST:event_btnQLDonHangActionPerformed

    private void btnQLHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHangHoaActionPerformed
        
        if(!StatusMenu.temp4){
            hideAllDropMenu();
            Drop4.setLocation(btnQLHangHoa.getLocation());
           
            Drop4.setSize(200, 135);
            StatusMenu.temp4=!StatusMenu.temp4;
        }else{
           hideAllDropMenu();
        }
    }//GEN-LAST:event_btnQLHangHoaActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        
        if(!StatusMenu.temp7){
            hideAllDropMenu();
            Drop7.setLocation(btnThongKe.getLocation());
            Drop7.setSize(150, 135);
            StatusMenu.temp7=!StatusMenu.temp7;
        }else{
            hideAllDropMenu();
        }
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangHoaActionPerformed
    	AddContent.addContent(new HangHoaPage());
    }//GEN-LAST:event_btnHangHoaActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new NhapHangPage());
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void lblTienIchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienIchMouseEntered
        lblTienIch.setFont(new Font(lblTienIch.getName(), Font.BOLD, lblTienIch.getFont().getSize()));
    }//GEN-LAST:event_lblTienIchMouseEntered

    private void lblTienIchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienIchMouseExited
        lblTienIch.setFont(btnBanHang.getFont());
    }//GEN-LAST:event_lblTienIchMouseExited

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered
        lblUser.setFont(new Font(lblTienIch.getName(), Font.BOLD, lblTienIch.getFont().getSize()));
    }//GEN-LAST:event_lblUserMouseEntered

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        lblUser.setFont(btnBanHang.getFont());
    }//GEN-LAST:event_lblUserMouseExited
    
    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt){
        btnTrangChu.setBackground(ColorSample.gbHover);
    }
    
    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt){
        btnTrangChu.setBackground(ColorSample.gb);
    }
    
    private void btnBanHangMouseEntered(java.awt.event.MouseEvent evt){
        btnBanHang.setBackground(ColorSample.gbHover);
    }
    
    private void btnBanHangMouseExited(java.awt.event.MouseEvent evt){
        btnBanHang.setBackground(ColorSample.gb);
    }
    
    private void btnQLDonHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDonHangMouseEntered
        btnQLDonHang.setBackground(ColorSample.gbHover);
    }//GEN-LAST:event_btnQLDonHangMouseEntered

    private void btnQLDonHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDonHangMouseExited
        btnQLDonHang.setBackground(ColorSample.gb);
    }//GEN-LAST:event_btnQLDonHangMouseExited

    private void btnQLHangHoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLHangHoaMouseEntered
         btnQLHangHoa.setBackground(ColorSample.gbHover);
    }//GEN-LAST:event_btnQLHangHoaMouseEntered

    private void btnQLHangHoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLHangHoaMouseExited
         btnQLHangHoa.setBackground(ColorSample.gb);
    }//GEN-LAST:event_btnQLHangHoaMouseExited

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
       btnThongKe.setBackground(ColorSample.gbHover);
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        btnThongKe.setBackground(ColorSample.gb);
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseClicked
         hideAllDropMenu();
    }//GEN-LAST:event_btnTrangChuMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
         hideAllDropMenu();
    }//GEN-LAST:event_btnBanHangMouseClicked
    private void pnlMainMouseEntered(java.awt.event.MouseEvent evt) {
                
            }
    private void btnXuatTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatTraActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new XuatTraPage());
        
        

    }//GEN-LAST:event_btnXuatTraActionPerformed

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
    	AddContent.addContent(new DoiMatKhauPage());
    }//GEN-LAST:event_lblUserMouseClicked

    private void pnlBodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBodyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBodyMouseClicked

    private void btnTheoHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheoHangHoaActionPerformed
        // TODO add your handling code here:
        AddContent.addContent(new ThongKeHangHoaPage());
    }//GEN-LAST:event_btnTheoHangHoaActionPerformed

    private void btnTheoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheoCPActionPerformed
        // TODO add your handling code here:
       AddContent.addContent(new ThongKeChiPhi());
    }//GEN-LAST:event_btnTheoCPActionPerformed

    private void btnTheoLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheoLNActionPerformed
        // TODO add your handling code here:
        AddContent.addContent(new ThongKeLoiNhuan());
    }//GEN-LAST:event_btnTheoLNActionPerformed

    private void lblTienIchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTienIchMouseClicked
        // TODO add your handling code here:
    	openHtmlFile();
    }//GEN-LAST:event_lblTienIchMouseClicked
    private void openHtmlFile() {
        try {
            File htmlFile = new File("utilities_html/html/index.html");
            if (htmlFile.exists()) {
                Desktop.getDesktop().browse(htmlFile.toURI());
            } else {
                System.out.println("File not found!");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void setFontAll(Font font){
        lblTienIch.setFont(font);
        lblUser.setFont(font);

    
        btnHangHoa.setFont(font);
        

        btnNhapHang.setFont(font);
     
        btnXuatTra.setFont(font);
        btnTrangChu.setFont(font);
        btnBanHang.setFont(font);
        btnTheoHangHoa.setFont(font);
        btnTheoLN.setFont(font);
        btnTheoCP.setFont(font);
        btnQLDonHang.setFont(font);
        btnQLHangHoa.setFont(font);
       
        btnThongKe.setFont(font);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	RootFrame rootFrame = new RootFrame();
            	rootFrame.setExtendedState(JFrame.MAXIMIZED_BOTH); // Hiển thị cửa sổ trong chế độ toàn màn hình
                rootFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Drop4;
    private javax.swing.JPanel Drop7;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnHangHoa;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnQLDonHang;
    private javax.swing.JButton btnQLHangHoa;
    private javax.swing.JButton btnTheoCP;
    private javax.swing.JButton btnTheoHangHoa;
    private javax.swing.JButton btnTheoLN;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXuatTra;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTienIch;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderMenu;
    private javax.swing.JPanel pnlHeaderTop;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
