/*
int row = tbl_HH.getSelectedRow();
				doDuLieuVaoComboBoxDonViTinh(model_HH.getValueAt(row, 1).toString()); * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

import components.AddContent;
import components.ButtonColumnUtil;
import components.ButtonRender;
import components.FormatJtable;
import components.Formater;
import components.NumericDocumentFilter;
import components.ResizeContent;
import components.SpinnerEditor;
import components.TableActionCellEditor;
import components.TableActionEvent;

import dao.HangHoaDao;

import entities.HangHoa;


/**
 *
 * @author Admin
 */
public class TaoHangHoaPage extends javax.swing.JPanel {


	private HangHoaDao hangHoa_dao = new HangHoaDao();


	/**
	 * Creates new form TaoHangHoa2
	 */
	public TaoHangHoaPage() {
		initComponents();
		ResizeContent.resizeContent(this);
		setFont();

	}
	private void setFont() {
		// TODO Auto-generated method stub

		Font font = new Font(jLabel2.getFont().getFontName(), Font.BOLD, 16);
		
		txt_donViTinh.setFont(font);
		txt_giaBan.setFont(font);
		txt_maHangHoa.setFont(font);
		txt_maVach.setFont(font);
		txt_moTa.setFont(font);
		txt_nhomHH.setFont(font);
		txt_soLuongCanhBao.setFont(font);
		txt_soLuongDinhMuc1.setFont(font);
		txt_tenHangHoa1.setFont(font);
		
		txt_soLuongDinhMuc1.setEditable(false);
		((AbstractDocument) txt_soLuongCanhBao.getDocument()).setDocumentFilter(new NumericDocumentFilter());
		((AbstractDocument) txt_soLuongDinhMuc1.getDocument()).setDocumentFilter(new NumericDocumentFilter());
		((AbstractDocument) txt_giaBan.getDocument()).setDocumentFilter(new NumericDocumentFilter());
	}
	
	public void showMessage(String s) {
		JOptionPane.showMessageDialog(this, s);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txt_maHangHoa = new javax.swing.JTextField();
        txt_nhomHH = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        txt_tenHangHoa1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_soLuongCanhBao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_moTa = new javax.swing.JTextField();
        txt_soLuongDinhMuc1 = new javax.swing.JTextField();
        txt_donViTinh = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        txt_giaBan = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txt_maVach = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        btn_Luu = new javax.swing.JButton();
        btn_Dong = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1940, 770));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1940, 450));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel51.setText("Mã Hàng Hoá");

        jLabel57.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel57.setText("Tên hàng hoá");

        jLabel59.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel59.setText("Mô tả");

        txt_maHangHoa.setEditable(false);
        txt_maHangHoa.setText("Mã tự động\n");
        txt_maHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        txt_nhomHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel62.setText("Nhóm hàng hoá");

        txt_tenHangHoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenHangHoa1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Số lượng định mức");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Số lượng cảnh báo");

        txt_soLuongCanhBao.setText("1");
        txt_soLuongCanhBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongCanhBaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Tạo hàng hóa mới");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Thông tin hàng hoá");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.red));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_moTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_moTajTextField5ActionPerformed(evt);
            }
        });

        txt_soLuongDinhMuc1.setEditable(false);
        txt_soLuongDinhMuc1.setText("0");

        txt_donViTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_donViTinhjTextField5ActionPerformed(evt);
            }
        });

        jLabel63.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel63.setText("Đơn vị tính");

        txt_giaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giaBanjTextField5ActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel64.setText("Giá bán");

        txt_maVach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maVachjTextField5ActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel65.setText("Mã vạch");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlHeaderLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel64)
                                    .addComponent(jLabel65)
                                    .addComponent(txt_donViTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                    .addComponent(txt_maVach))
                                .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(129, 129, 129)
                            .addComponent(txt_moTa, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1521, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHeaderLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel57)
                                    .addComponent(txt_tenHangHoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlHeaderLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(txt_nhomHH, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(129, 129, 129)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel51)
                            .addComponent(txt_maHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel59)
                            .addComponent(txt_soLuongDinhMuc1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(txt_soLuongCanhBao))))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenHangHoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soLuongDinhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soLuongCanhBao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nhomHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_donViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_moTa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_maVach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        txt_soLuongDinhMuc1.setEditable(false);



        add(pnlHeader, java.awt.BorderLayout.CENTER);

        pnlFooter.setBackground(new java.awt.Color(193, 219, 208));
        pnlFooter.setMinimumSize(new java.awt.Dimension(0, 50));
        pnlFooter.setPreferredSize(new java.awt.Dimension(1940, 60));

        btn_Luu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_Luu.setText("Lưu ");
        btn_Luu.setPreferredSize(new java.awt.Dimension(72, 40));
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        btn_Dong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_Dong.setText("Trở về");
        btn_Dong.setPreferredSize(new java.awt.Dimension(72, 40));
        btn_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(1557, Short.MAX_VALUE)
                .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_Dong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Dong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        add(pnlFooter, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_donViTinhjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_donViTinhjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_donViTinhjTextField5ActionPerformed

    private void txt_giaBanjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giaBanjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giaBanjTextField5ActionPerformed

    private void txt_maVachjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maVachjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maVachjTextField5ActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
    	if (validData()) {
			
			String tenHH = txt_tenHangHoa1.getText().trim();
			String nhom = txt_nhomHH.getText().trim();
			String moTa = txt_moTa.getText().trim();

			int soLuongCB = 0;
			if(!txt_soLuongCanhBao.getText().isEmpty())			
				 soLuongCB = Integer.parseInt(txt_soLuongCanhBao.getText().replaceAll(",", ""));
			String dvt = txt_donViTinh.getText().trim();
			double giaBan = Double.parseDouble(txt_giaBan.getText().replaceAll(",", ""));
			String maVach = txt_maVach.getText().trim();
	
			HangHoa hh = new HangHoa(null, tenHH, nhom, dvt, moTa, maVach, giaBan, 0, soLuongCB);
			
			if(hangHoa_dao.themHangHoa(hh)) {
				showMessage("Đã tạo hàng hóa mới!");
				clear();
			}else
				showMessage("Lỗi tạo hàng hóa mới!");
			

		}
    }//GEN-LAST:event_btn_LuuActionPerformed

	
	private void clear() {
		// TODO Auto-generated method stub
		txt_donViTinh.setText("");
		txt_giaBan.setText("");
		txt_maVach.setText("");
		txt_moTa.setText("");
		txt_nhomHH.setText("");
		txt_soLuongCanhBao.setText("1");
		txt_tenHangHoa1.setText("");
		txt_tenHangHoa1.requestFocus();
	}
	private boolean validData() {
		// TODO Auto-generated method stub
		if (txt_tenHangHoa1.getText().trim().isEmpty()) {
			showMessage("Tên hàng hóa không được để trống");
			txt_tenHangHoa1.requestFocus();
			txt_tenHangHoa1.selectAll();
			return false;
		}
		if(txt_giaBan.getText().isEmpty()) {
			showMessage("Giá bán không được để trống");
			txt_giaBan.requestFocus();
			return false;
		}

		return true;
	}

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox2ActionPerformed

	private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField8ActionPerformed

	private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField7ActionPerformed

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField4ActionPerformed

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void txt_tenHangHoa1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_tenHangHoa1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_tenHangHoa1ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	private void txt_soLuongCanhBaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_soLuongCanhBaoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_soLuongCanhBaoActionPerformed

	private void txt_moTajTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_moTajTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_moTajTextField5ActionPerformed

	private void btn_xoaDVTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_xoaDVTActionPerformed
		// TODO add your handling code here:
		
	}// GEN-LAST:event_btn_xoaDVTActionPerformed

	private void btn_DongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_DongActionPerformed
		// TODO add your handling code here:
		AddContent.addContent(new HangHoaPage());
	}// GEN-LAST:event_btn_DongActionPerformed

	private void txt_vatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_vatActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_vatActionPerformed

	private void btn_themDVTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_themDVTActionPerformed
		// TODO add your handling code here:

		

	}// GEN-LAST:event_btn_themDVTActionPerformed

	private void txt_thuocMauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_thuocMauActionPerformed
		// TODO add your handling code here:
    	
  
    	
    	
	}// GEN-LAST:event_txt_thuocMauActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dong;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    protected static javax.swing.JTextField txt_donViTinh;
    protected static javax.swing.JTextField txt_giaBan;
    protected static javax.swing.JTextField txt_maHangHoa;
    protected static javax.swing.JTextField txt_maVach;
    protected static javax.swing.JTextField txt_moTa;
    protected static javax.swing.JTextField txt_nhomHH;
    protected static javax.swing.JTextField txt_soLuongCanhBao;
    protected static javax.swing.JTextField txt_soLuongDinhMuc1;
    protected static javax.swing.JTextField txt_tenHangHoa1;
    // End of variables declaration//GEN-END:variables
}
