/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.ChiTietPhieuNhapHangDao;

import dao.HangHoaDao;
import dao.LoHangDao;

import dao.PhieuNhapHangDao;
import entities.ChiTietPhieuNhapHang;
import entities.HangHoa;
import entities.LoHang;

import entities.PhieuNhapHang;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.text.AbstractDocument;

import com.github.lgooddatepicker.components.DatePicker;

import components.AddContent;
import components.ButtonRender;
import components.ComboboxCellEditor;
import components.DatePickerCellEditor;
import components.DatePickerEditor;
import components.DatePickerRenderer;
import components.FormatJtable;
import components.Formater;
import components.NumericCellEditor;
import components.NumericDocumentFilter;
import components.ResizeContent;
import components.SpinnerEditor;
import components.TableActionCellEditor;
import components.TableActionEvent;

/**
 *
 * @author ACER
 */
public class XemPhieuXuatTraPage extends javax.swing.JPanel {


	
	protected JTable tbl_HH;
	protected DefaultTableModel model_HH;

	
	/**
     * Creates new form NhapHang
     */
    public XemPhieuXuatTraPage() {
        initComponents();
        new ResizeContent().resizeContent(this);
        addNhapHangTable();
        setFont();
    
    }
    private void setFont() {
		// TODO Auto-generated method stub
    	Font font = new Font("Arial", Font.BOLD, 16);
    	txt_chietKhau.setFont(font);
    	txt_ghiChu.setFont(font);
    	txt_tongThanhTien.setFont(font);
    	txt_tongTienNhap.setFont(font);
    	((AbstractDocument) txt_tongThanhTien.getDocument()).setDocumentFilter(new NumericDocumentFilter());
    	((AbstractDocument) txt_tongTienNhap.getDocument()).setDocumentFilter(new NumericDocumentFilter());
    }
	

    private void reload() {
		// TODO Auto-generated method stub
		
	}
    private void addNhapHangTable() {
		// TODO Auto-generated method stub
    	
    	String[] colNames = {"STT", "Mã HH", "Tên HH", "Số lô","Ngày sản xuất", "Hạn sử dụng", "DVT", "Số lượng xuất", "Giá xuất", "VAT (%)", "Chiết khấu", "Thành tiền"};
        
        model_HH = new DefaultTableModel(colNames, 0);
        tbl_HH = new JTable(model_HH);
        FormatJtable.setFontJtable(tbl_HH);
        FormatJtable.setCellEditable(tbl_HH);
        JScrollPane js_tableHangHoa = new JScrollPane(tbl_HH);
        
        if (tbl_HH.getColumnModel().getColumnCount() > 0) {
        	tbl_HH.getColumnModel().getColumn(0).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(1).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(2).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(3).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(4).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(5).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(6).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(7).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(8).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(9).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(10).setResizable(false);
        	tbl_HH.getColumnModel().getColumn(11).setResizable(false);
        }
        
        tbl_HH.getColumnModel().getColumn(0).setPreferredWidth(50);

        /*
         * add combobox vao table
         */
       
        
        JTableHeader headerTable =  tbl_HH.getTableHeader();
		headerTable.setPreferredSize(new Dimension(headerTable.getPreferredSize().width, 40));
		headerTable.setBackground(Color.white);
		tbl_HH.setRowHeight(40);
		
//		setCellEditable();
        jP_tableContent.add(js_tableHangHoa, BorderLayout.CENTER);
        
		
	}
   



	

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_header = new javax.swing.JPanel();
        jL_maPhieuNhap = new javax.swing.JLabel();
        jL_ghiChu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        jL_tongTienNhap = new javax.swing.JLabel();
        txt_tongTienNhap = new javax.swing.JTextField();
        txt_maPhieuNhap1 = new javax.swing.JTextField();
        jP_body = new javax.swing.JPanel();
        jP_bodyHeader = new javax.swing.JPanel();
        txt_chietKhau = new javax.swing.JTextField();
        jL_chietKhau = new javax.swing.JLabel();
        txt_tongThanhTien = new javax.swing.JTextField();
        jL_tongThanhTien = new javax.swing.JLabel();
        btn_thoat1 = new javax.swing.JButton();
        jL_ngayLap = new javax.swing.JLabel();
        jL_gioNhap = new javax.swing.JLabel();
        txt_gio = new javax.swing.JTextField();
        txt_Ngay = new javax.swing.JTextField();
        jP_tableContent = new javax.swing.JPanel();
        jL_chiTietPhieuGhi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1860, 700));
        setLayout(new java.awt.BorderLayout());

        jP_header.setBackground(new java.awt.Color(255, 255, 255));
        jP_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_maPhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jL_maPhieuNhap.setText("Mã phiếu xuất:");
        jP_header.add(jL_maPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jL_ghiChu.setText("Ghi chú:");
        jL_ghiChu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jP_header.add(jL_ghiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, -1));

        txt_ghiChu.setEditable(false);
        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        jP_header.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 350, 35));

        jL_tongTienNhap.setText("Tổng tiền hàng:");
        jL_tongTienNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jP_header.add(jL_tongTienNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, -1));

        txt_tongTienNhap.setEditable(false);
        txt_tongTienNhap.setBackground(new java.awt.Color(255, 255, 255));
        txt_tongTienNhap.setToolTipText("");
        txt_tongTienNhap.setPreferredSize(new java.awt.Dimension(150, 35));
        txt_tongTienNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tongTienNhapActionPerformed(evt);
            }
        });
        jP_header.add(txt_tongTienNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 280, -1));
        txt_tongTienNhap.setEditable(false);

        txt_maPhieuNhap1.setEditable(false);
        txt_maPhieuNhap1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_maPhieuNhap1.setToolTipText("Mã tự phát sinh");
        txt_maPhieuNhap1.setPreferredSize(new java.awt.Dimension(400, 35));
        txt_maPhieuNhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maPhieuNhap1ActionPerformed(evt);
            }
        });
        jP_header.add(txt_maPhieuNhap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 480, -1));

        add(jP_header, java.awt.BorderLayout.PAGE_START);

        jP_body.setBackground(new java.awt.Color(255, 255, 255));
        jP_body.setLayout(new java.awt.BorderLayout(0, 10));

        jP_bodyHeader.setBackground(new java.awt.Color(255, 255, 255));
        jP_bodyHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_chietKhau.setEditable(false);
        txt_chietKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_chietKhau.setPreferredSize(new java.awt.Dimension(100, 35));
        txt_chietKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chietKhauActionPerformed(evt);
            }
        });
        jP_bodyHeader.add(txt_chietKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 280, -1));
        txt_chietKhau.setEditable(false);

        jL_chietKhau.setText("Tổng giảm giá:");
        jL_chietKhau.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jP_bodyHeader.add(jL_chietKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        txt_tongThanhTien.setEditable(false);
        txt_tongThanhTien.setBackground(new java.awt.Color(255, 255, 255));
        txt_tongThanhTien.setToolTipText("");
        txt_tongThanhTien.setPreferredSize(new java.awt.Dimension(150, 35));
        jP_bodyHeader.add(txt_tongThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 350, 35));
        txt_tongThanhTien.setEditable(false);

        jL_tongThanhTien.setBackground(new java.awt.Color(255, 255, 255));
        jL_tongThanhTien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_tongThanhTien.setForeground(new java.awt.Color(255, 102, 102));
        jL_tongThanhTien.setText("Tổng thành tiền");
        jP_bodyHeader.add(jL_tongThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 180, 30));

        btn_thoat1.setText("Thoát");
        btn_thoat1.setBackground(new java.awt.Color(193, 219, 208));
        btn_thoat1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_thoat1.setForeground(new java.awt.Color(218, 80, 90));
        btn_thoat1.setPreferredSize(new java.awt.Dimension(100, 45));
        btn_thoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat1ActionPerformed(evt);
            }
        });
        jP_bodyHeader.add(btn_thoat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 40, 130, 35));

        jL_ngayLap.setText("Ngày lập phiếu:");
        jL_ngayLap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jP_bodyHeader.add(jL_ngayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, -1));

        jL_gioNhap.setText("Giờ nhập phiếu:");
        jL_gioNhap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jP_bodyHeader.add(jL_gioNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 180, -1));

        txt_gio.setEditable(false);
        txt_gio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_gio.setToolTipText("Mã tự phát sinh");
        txt_gio.setPreferredSize(new java.awt.Dimension(400, 35));
        txt_gio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gioActionPerformed(evt);
            }
        });
        jP_bodyHeader.add(txt_gio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 180, -1));

        txt_Ngay.setEditable(false);
        txt_Ngay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_Ngay.setToolTipText("Mã tự phát sinh");
        txt_Ngay.setPreferredSize(new java.awt.Dimension(400, 35));
        txt_Ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NgayActionPerformed(evt);
            }
        });
        jP_bodyHeader.add(txt_Ngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, -1));

        jP_body.add(jP_bodyHeader, java.awt.BorderLayout.PAGE_START);

        jP_tableContent.setLayout(new java.awt.BorderLayout(0, 10));

        jL_chiTietPhieuGhi.setText("Chi tiết phiếu ghi");
        jL_chiTietPhieuGhi.setBackground(new java.awt.Color(255, 255, 255));
        jL_chiTietPhieuGhi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jP_tableContent.add(jL_chiTietPhieuGhi, java.awt.BorderLayout.NORTH);

        jP_body.add(jP_tableContent, java.awt.BorderLayout.CENTER);

        add(jP_body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void showMessage(String string) {
		// TODO Auto-generated method stub
		JOptionPane.showMessageDialog(this, string);
	}

	private void txt_chietKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chietKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chietKhauActionPerformed

    private void txt_tongTienNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tongTienNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tongTienNhapActionPerformed

   

   
	private void txt_gioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gioActionPerformed

    private void btn_thoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat1ActionPerformed
        // TODO add your handling code here:
    	AddContent.addContent(new XuatTraPage());
    }//GEN-LAST:event_btn_thoat1ActionPerformed

    private void txt_maPhieuNhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maPhieuNhap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maPhieuNhap1ActionPerformed

    private void txt_NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NgayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thoat1;
    private javax.swing.JLabel jL_chiTietPhieuGhi;
    private javax.swing.JLabel jL_chietKhau;
    private javax.swing.JLabel jL_ghiChu;
    private javax.swing.JLabel jL_gioNhap;
    private javax.swing.JLabel jL_maPhieuNhap;
    private javax.swing.JLabel jL_ngayLap;
    private javax.swing.JLabel jL_tongThanhTien;
    private javax.swing.JLabel jL_tongTienNhap;
    private javax.swing.JPanel jP_body;
    private javax.swing.JPanel jP_bodyHeader;
    private javax.swing.JPanel jP_header;
    private javax.swing.JPanel jP_tableContent;
    private javax.swing.JScrollPane jScrollPane2;
    protected static javax.swing.JTextField txt_Ngay;
    protected static javax.swing.JTextField txt_chietKhau;
    protected static javax.swing.JTextArea txt_ghiChu;
    protected static javax.swing.JTextField txt_gio;
    protected static javax.swing.JTextField txt_maPhieuNhap1;
    protected static javax.swing.JTextField txt_tongThanhTien;
    protected static javax.swing.JTextField txt_tongTienNhap;
    // End of variables declaration//GEN-END:variables
}
